framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
              options:
                auto_setup: false
                # for AMQP send to a separate exchange then queue
                exchange:
                  name: cand_d4uf
                  type: direct

            consumer_transport:
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
              options:
                auto_setup: false
                queues:
                  cand_d4uf_results: ~
              # -> If you wish to use custom serializer for this transport,
              # uncomment the next line:
              # serializer: App\Serializer\ExternalJsonSerializer

        routing:
          # Route your messages to the transports
          'App\Message\MyMessage' : [async, consumer_transport]
          # -> If you wish to use custom serializer for this transport,
          # remove the 'consumer_transport' from the array above.
