site_url: https://symfonyrabbitmqdoc.herokuapp.com/
site_name: Net2Grid's Assignment
site_author: 'Christopher Bekos'
site_description: Project documentation with Markdown.
repo_url: https://github.com/mpekchri/SymfonyRabbitMQ


nav:
    - Overview: index.md
    - Configuring Symfony: settings.md
    - Project Structure: structure.md
    - Application's Internals: internals.md
    - Using the Application: using.md
    # - Consuming API: consumingApi.md
    # - De-serializing API responses: serializeApi.md
    # - Sending messages to the queue: sendMessages.md
    # - Receiving messages from the queue: consumeMessages.md
    # - Saving to database: save.md
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml

markdown_extensions:
    - attr_list
    - admonition # check the docs: https://squidfunk.github.io/mkdocs-material/extensions/admonition/

extra_css:
    - extra.css
